language: perl
perl:     5.20
sudo:     false

addons:
  apt:
    packages:
      - libluajit-5.1-dev

env:
  global:
    - LUA_CFLAGS="-I/usr/include/luajit-2.0"
    - LUA_LIBS="-L/usr/lib/x86_64-linux-gnu -lluajit-5.1 -lm"
    - VER_APR=1.5.2
    - VER_APRUTIL=1.5.4
    - VER_HTTPD=2.4.18

install: true
script:  ./compile_and_test.sh
